{{- if  (eq .Values.global.env "dev") }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}-web-dev
  labels:
    app: {{ .Chart.Name }}-web-dev
spec:
  replicas: 1
  serviceName: {{ .Chart.Name }}-web-dev
  selector:
      matchLabels:
        app: {{ .Chart.Name }}-web-dev
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-web-dev
    spec:
      containers:
      - name: {{ .Chart.Name }}-web-dev
{{ tuple "calendar-web-dev" . | include "werf_container_image" | indent 8 }}
        envFrom:
        - configMapRef:
            name: config-values
        volumeMounts:
        - name: id-rsa-vcs
          mountPath: "/root/.ssh/id_rsa"
          subPath: "id_rsa" 
        - mountPath: /workspace
          name: workspace 
      volumes:
      - name: workspace
        hostPath:
          path: /.volumes/calendar-web-dev-workspace
      - name: id-rsa-vcs
        secret:
          secretName: id-rsa-vcs
          defaultMode: 0600
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service-web
  labels:
    app: {{ .Chart.Name }}-service-web
spec:
  clusterIP: None
  selector:
    app: {{ .Chart.Name }}-web-dev
  ports:
  - name: {{ .Chart.Name }}-web-dev
    port: 3000
    protocol: TCP
{{- else }}
{{- end }}